### ISSUE TITLE
mlflow issue

### ISSUE THREAD

**Issue by AyaHamdy** [mapa17/thousandVoices#1]
Thanks for your effort,
after i run this command: python3 deploy.py /mnt/DATA2/MultiSpeaker/thousandVoices-master/TTS/basemodel
an error with mlflow:
  File "deploy.py", line 63, in _deploy
    with open(model.context.artifacts["meta"], 'rb') as handle:
AttributeError: 'PyFuncModel' object has no attribute 'context'

**Comment by mapa17** [comment]
Hello,

did you package the model before trying to deploy it?
There are basically two steps

1) Model packaging (using MLflow)
Package the model using the artifacts in **TTS/artifacts**, and storing the package in **packages/test_deployment**
```
python TTS/pack.py TTS/artifacts packages/test_deployment
```

2) Model deployment
Deploy the packaged model in **packages/test_deployment** using a Flask server
```
python TTS/deploy.py packages/test_deployment
```

**Comment by mapa17** [comment]
I added a short description to the main README.md I hope that helps.

**Comment by AyaHamdy** [comment]
Thanks for your help,
but after i run your commands i still have an error at deployment stage:
  File "/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "TTS/deploy.py", line 77, in deploy
    app = _deploy(package)
  File "TTS/deploy.py", line 58, in _deploy
    with open(model.context.artifacts["meta"], 'rb') as handle:
AttributeError: 'PyFuncModel' object has no attribute 'context'

what's your mlflow release? am using last release=1.9.1

Solution:
pip install mlflow==1.8.0

**Comment by mapa17** [comment]
Thx for the response. I can confirm that upgrading mlflow to > 1.8.0 breaks the code.

**Comment by mapa17** [comment]
The issue should be fixed with 0b4408d
The current version works with mlflow >= 1.9

The origin of the issue is an interface change since mlflow 1.9, I have opened and issue for it at
https://github.com/mlflow/mlflow/issues/3031
